name: 'publish'

on:
  push:
    branches:
      - 'main'
    paths:
      - 'content/post/**'

concurrency:
  cancel-in-progress: true
  group: publish-${{ github.head_ref || github.ref }}

jobs:
  publish:
    name: publish new article
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: blogpub
        uses: protiumx/blogpub@v0.8.0
        with:
          articles_folder: content/post
          devto_api_key: ${{ secrets.DEVTO_API_KEY }}
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          medium_token: ${{ secrets.MEDIUM_TOKEN }}
          medium_user_id: ${{ secrets.MEDIUM_USER_ID }}
